### ISSUE TITLE
Doesn't work with Mirror 42.2.12

### ISSUE THREAD

**Issue by Morgan-6Freedom** [SoftwareGuy/Ignorance#79]
Hello.

In the readme you say that we should use the Mirror version that is on the asset store.
on the 06/08/2021 the version on the asset store is Mirror 42.2.12
I have imported Mirror 42.2.12 in a Unity 2019.4.24f1 empty project
I have imported Ignorance-v140b6.1-20210614.unitypackage
and this is what happen :

![image](https://user-images.githubusercontent.com/49686866/128508183-bb4daf33-dea2-4360-818c-77cb0e15da14.png)

**Comment by SoftwareGuy** [comment]
Looks like a compile define wasn't set correctly... hmm.
Allow me to check in the morning and I'll get back to you on this. :)

**Comment by SoftwareGuy** [comment]
Cannot replicate. Please look below and see if I missed anything.

What I did:
- Make a new project using the Blank 3D template using Unity Hub
- Went to Unity Asset Store and grabbed the latest version of Mirror
- Imported Mirror and waited for everything to compile successfully
- Downloaded 1.4.0b6.1 and imported everything from the Unity Package
- Waited for compile to finish
- Only log item was due to a obsolete warning, no major errors.
- Tried a demo scene, no problems detected.

I require further information before I can look into this further.

**Comment by SoftwareGuy** [comment]
Stale and obsolete Mirror version now in 2022. Closing.
